version: "3.8"
services:
  smocks-backend:
    container_name: smocks-backend
    ports:
      - 8000:8000
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    environment:
      - SMOCKS_SECRET_KEY=${SMOCKS_SECRET_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - TIDAL_CLIENT_ID=${TIDAL_CLIENT_ID}
      - TIDAL_CLIENT_SECRET=${TIDAL_CLIENT_SECRET}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
      - GOOGLE_SEARCH_BILLBOARD_ENGINER=${GOOGLE_SEARCH_BILLBOARD_ENGINER}
